/**
 * LE COMMENTATEUR PINCE-SANS-RIRE : des pièces SUPPLÉMENTAIRES pour js/commentaire.js.
 *
 * Même forme, mêmes étiquettes, mêmes gabarits que les banques de commentaire.js ; rien
 * n'est inventé ici que le moteur de phrases ne sache déjà tirer. HUMOUR a une clé par
 * banque existante (CRI_ARRET, ACTIONS_TIREUR, CONTEXTE_BUT…), et commentaire.js n'a qu'à
 * les pousser dans les siennes : une pièce d'ici se tire comme une pièce de là-bas.
 *
 * Le ton : un format de télé sérieux (phrases propres, analyse), un contenu qui prend
 * l'absurde et le banal du hockey très au sérieux. Jamais de gag annoncé, aucun vrai nom.
 * Les recherchistes, réalisateurs et statisticiens de la production restent des fonctions,
 * pas des personnes.
 *
 * LA RÈGLE DE VÉRITÉ : une pièce ne se dit que pour des événements où elle est vraie.
 * Les banques à condition (CHUTE_ARRET_SERRE, CONTEXTE_BUT.devant…) ne disent que ce que
 * leur condition garantit : jamais un nombre de buts là où le score peut être 0-0, jamais
 * « prolongation » dans COULEUR_FIN.prolongation (la phrase d'avant vient de la nommer).
 * Les banques que commentaire.js ne passe PAS par remplir() (CONTEXTE_BUT.doublé, .chapeau, .an et .dn, COULEUR_PUNITION,
 * COULEUR_PUNITION_TARD, RETOUR_EQUIPE, COULEUR_PERIODE.egal, COULEUR_PERIODE.prolongation,
 * DEBUT, COULEUR_DEBUT, FIN_MATCH, COULEUR_FIN.serre, COULEUR_FIN.prolongation,
 * ISSUE_BAGARRE.nul, COULEUR_BAGARRE.nul) n'ont aucun gabarit. Et une équipe n'est sujet
 * d'une phrase que par « de {eq} », « pour {eq} », « à {eq} » : l'article se règle seul.
 */

export const HUMOUR = {
  /* ---------- les arrêts dangereux ---------- */
  CRI_ARRET: [
    'Voilà qui est notable.', 'Un instant, s\'il vous plaît.', 'On prend note.', 'Pardon ?', 'Ceci mérite un temps d\'arrêt.',
    'Effectivement.', 'Fait à signaler.', 'Intéressant.', 'Je n\'ai pas d\'objection.', 'La production confirme.', 'Voyons voir.',
    'C\'est ce qu\'on appelle une occasion.', 'Rien de grave, en apparence.', 'Notons-le.', 'Un peu d\'agitation.',
    'Disons que ça se discute.', 'Je répète pour les gens à la maison.', 'Oui, oui, c\'était sérieux.', 'Ça mérite un paragraphe.',
    'Observation du moment.', 'Rien à signaler, sauf ça.', 'Alerte d\'intensité moyenne.', 'On me signale du mouvement.',
    'Mesdames et messieurs, une rondelle.', 'Voilà un développement.',
  ],
  ACTIONS_TIREUR: [
    // Les avants, quel que soit leur style.
    ['{t} hérite de la rondelle avec une courtoisie suspecte', 'F'],
    ['{t} se présente devant le filet comme à un rendez-vous déjà confirmé', 'F'],
    ['{t} lance, et il y a lieu de croire que c\'était voulu', 'F'],
    ['{t} trouve de l\'espace dans un coin que personne ne surveillait', 'F'],
    ['{t} reçoit la rondelle et prend une décision, ce qui est déjà un progrès', 'F'],
    ['{t} décoche un tir que le plan de match ne prévoyait pas', 'F'],
    ['{t} s\'approprie un morceau de l\'enclave', 'F'],
    ['{t} tente quelque chose, et on lui reconnaît l\'intention', 'F'],
    ['{t} cadre son tir avec la rigueur d\'un arpenteur', 'F'],
    ['{t} choisit son coin, par principe', 'F'],
    ['{t} s\'installe dans l\'enclave sans avoir sonné', 'F'],
    ['{t} se retrouve en bonne position, ce qu\'on lui reprochera peu', 'F'],
    // Les défenseurs, quel que soit leur style.
    ['{t} avance d\'un pas de plus, et c\'est ce qui le rend dangereux', 'D'],
    ['{t} se rappelle qu\'un défenseur a aussi le droit de lancer', 'D'],
    ['{t} profite d\'une rondelle qui traînait pour tirer', 'D'],
    ['{t} lance de la ligne bleue, sous l\'œil attentif de son entraîneur', 'D'],
    ['{t} quitte son poste pour une démarche offensive officielle', 'D'],
    ['{t} tire de la pointe après mûre réflexion', 'D'],
    ['{t} s\'aventure en territoire offensif avec une carte à jour', 'D'],
    ['{t} lance de loin, et c\'est dans sa description de tâches', 'D'],
    // Sans poste ni style.
    ['{t} lance, et les statisticiens en prennent note', ''],
    ['{t} tire à un endroit que la rondelle jugeait raisonnable', ''],
    ['{t} dépose un tir à l\'adresse indiquée', ''],
    ['{t} propose un tir, et le gardien est invité à répondre', ''],
    // Les styles.
    ['{t} arme un lancer frappé dont le bruit précède l\'arrivée', 'canon'],
    ['{t} lance avec une force que le règlement ne mentionne pas', 'canon'],
    ['{t} frappe la rondelle comme on règle un différend', 'canon'],
    ['{t} vise un coin précis dont il connaît l\'adresse', 'tireur'],
    ['{t} choisit son tir avec la minutie d\'un notaire', 'tireur'],
    ['{t} rappelle d\'un tir qu\'il est payé pour ça', 'tireur'],
    ['{t} hésite savamment avant de tirer', 'F fab'],
    ['{t} feinte la passe, puis se souvient qu\'il peut tirer', 'F fab'],
    ['{t} ralentit le jeu pour mieux le contrarier', 'F fab'],
    ['{t} dépose un geste raffiné, au cas où quelqu\'un filmerait', 'F fab'],
    ['{t} passe le défenseur à la vitesse d\'une urgence', 'F rapide'],
    ['{t} arrive avant que l\'avis de départ soit publié', 'F rapide'],
    ['{t} laisse son couvreur méditer sur la distance', 'F rapide'],
    ['{t} profite d\'un revirement avec une promptitude remarquable', 'F rapide contre'],
    ['{t} transforme une erreur adverse en échéance', 'F contre'],
    ['{t} se lance dans la transition avant que quiconque ait fini de la regretter', 'F contre'],
    // Les systèmes.
    ['{t} lance de la pointe, selon une procédure établie', 'D bleue'],
    ['{t} se place devant le filet pour une déviation soigneusement calculée', 'F bleue'],
    ['{t} capte une passe de la pointe qui était annoncée dans les documents', 'F bleue'],
    ['{t} émerge de derrière le filet, déjà au courant', 'F derriere'],
    ['{t} reçoit une passe de derrière la ligne des buts, comme au programme', 'F derriere'],
    ['{t} contourne le filet avec la patience d\'un comptable', 'F derriere'],
    ['{t} conclut un échange de passes courtes d\'une politesse exemplaire', 'F courtes'],
    ['{t} reçoit une passe de trois mètres et la traite avec égards', 'F courtes'],
    ['{t} termine un jeu où personne n\'a élevé la voix', 'F courtes'],
    ['{t} dérobe la rondelle à une défensive encore en train de s\'installer', 'F echec'],
    ['{t} profite d\'une pression avant dont personne ne s\'était plaint', 'F echec'],
    ['{t} ramasse une rondelle que l\'échec avant avait rendue disponible', 'F echec'],
    ['{t} surgit après quarante secondes de patience organisée', 'F defensive'],
    ['{t} attend le moment prévu, puis le saisit', 'F defensive'],
    // Les situations.
    ['{t} reçoit la rondelle à l\'avantage numérique et la traite avec égards', 'AN'],
    ['{t} lance en avantage numérique, comme le règlement le permet', 'AN'],
    ['{t} profite de la supériorité numérique pour parler sans être interrompu', 'F AN'],
    ['{t} lance de la pointe sur l\'avantage numérique, par souci de régularité', 'D AN'],
    ['{t} tire en désavantage numérique, ce qui n\'était pas dans le contrat', 'F DN'],
    ['{t} sort de la boîte pour une visite imprévue', 'F DN'],
  ],
  ISSUE_GARDIEN: [
    '{g} règle la question sans lever la voix', '{g} fait exactement ce pour quoi il est payé', '{g} occupe l\'espace conformément au bail',
    '{g} tend la jambière au bon endroit, par pur hasard anatomique', '{g} refuse la rondelle poliment',
    '{g} traite le dossier en une seule manœuvre', '{g} s\'oppose avec un calme presque administratif',
    '{g} avait prévu le coup et l\'a consigné quelque part', '{g} met fin à la discussion',
    '{g} déplace son équipement vers la rondelle, ce qui s\'avère concluant', '{g} rappelle que le filet est un espace occupé',
    '{g} se trouve exactement là où la rondelle voulait aller', '{g} accepte la rondelle, sans enthousiasme',
    '{g} ne bronche pas, ce qui est sa façon de bouger', '{g} replace ses jambières, comme si de rien n\'était',
    '{g} procède à un arrêt dans les règles de l\'art', '{g} neutralise la menace et passe au point suivant',
    '{g} est resté debout, par conviction', '{g} absorbe l\'information et la renvoie en coin', '{g} garde son sang-froid et la rondelle',
    '{g} intervient au moment prévu à l\'horaire', '{g} dévie ça avec une désinvolture mesurée', '{g} ferme le dossier d\'un geste du gant',
    '{g} n\'a pas jugé nécessaire de s\'énerver', '{g} répond à la question par la négative', '{g} oppose son plastron aux revendications du tireur',
    '{g} maintient la situation sous contrôle', '{g} tombe du bon côté, comme souvent', '{g} fait le mur avec beaucoup de constance',
    '{g} se contente de l\'essentiel, et l\'essentiel suffit', '{g} laisse la rondelle mourir doucement contre lui',
    '{g} se déploie en étoile, comme prévu', '{g} parvient à être à deux endroits, ou presque', '{g} lit l\'intention et la dépose dans le coin',
    '{g} s\'étend à plat, avec dignité', '{g} reste maître de la situation, et de la rondelle', '{g} accomplit une formalité essentielle',
    '{g} donne une leçon de positionnement', '{g} se couche sur le côté et change l\'avenir de la rondelle', '{g} lui oppose une fin de non-recevoir',
    '{g} dépose la rondelle loin de toute contestation', '{g} jette un coup d\'œil vers le tableau, rassuré', '{g} ne cède rien, pas même un regard',
    '{g} a son mot à dire, et c\'est non', '{g} s\'assure que le pointage reste ce qu\'il était', '{g} agrandit le filet par sa seule présence',
    '{g} n\'a rien promis à personne', '{g} intercepte l\'espoir du tireur en plein vol', '{g} règle ça avec un naturel déconcertant',
    '{g} s\'acquitte de la tâche sans demander de reconnaissance', '{g} garde les bras où ils étaient utiles',
  ],
  CHUTE_ARRET: [
    'Le tableau indicateur n\'a pas bougé, et c\'est ce qu\'on retiendra.', 'Rien ne sera consigné au pointage, mais le moment méritait mention.',
    'Le chroniqueur de couleur y voit un tournant, sans préciser lequel.', 'On n\'en parlera pas à la pause, ce qui est dommage.',
    'Dans une autre vie, c\'était un but.', 'Un arrêt de plus au dossier, et {g} ne bronche pas.', '{t} y repensera dans l\'autobus.',
    '{t} retiendra la leçon, sans trop savoir laquelle.', '{g} n\'en parlera pas au vestiaire, par modestie.',
    'Le banc de {att} prend la chose avec un stoïcisme de façade.', 'Le banc de {def} respire de nouveau.',
    'Les partisans de {def} se rassoient lentement.', 'Du côté de {att}, on note l\'intention.',
    'Un arrêt, donc, et non un but, comme certains l\'espéraient.', 'Les caméras confirment que la rondelle n\'est pas entrée.',
    'Du côté de {def}, c\'est le genre de seconde qui se paie cher.', 'C\'est ce qu\'on appelle une conversation franche entre {t} et {g}.',
    'On le dit sans exagérer : la rondelle est restée à l\'extérieur.', 'Prenons un moment pour apprécier la physique de la chose.',
    'Le réalisateur reprendra ça au ralenti, par habitude.', 'Je ne dis pas que c\'était un arrêt facile, je dis qu\'il a eu lieu.',
    'La rondelle repart, un peu déçue.', 'Le banc de {att} y croyait, à sa manière discrète.', 'Une occasion qui fera, au mieux, un souvenir.',
    'Ça se termine comme ça se termine souvent : sans but.', 'Le recherchiste cherche encore un précédent, sans conviction.',
    'On peut parler d\'un échange de vues entre le tireur et le gardien.', 'La logique est sauve, du moins pour le moment.',
    'Les arbitres ne sont pas intervenus, et pour cause.', 'Au ralenti, ça ne s\'améliore pas pour le tireur.',
    'Un moment fort, dans la catégorie des moments qui ne changent rien.', 'Ce n\'est pas un but, mais ce n\'est pas rien non plus.',
    'La rondelle est maintenant en d\'autres mains, au sens large.', 'Une séquence qui aurait pu mal finir pour {def}.',
    'Les spécialistes parleront d\'un arrêt, les autres aussi.', 'Voilà un arrêt de bonne facture, dans le sens administratif.',
    'On reste dans le cadre de la loi, le gardien l\'a bien lue.', 'L\'analyste de la production lève un sourcil, puis le baisse.',
    'Sur le banc de {att}, quelqu\'un a probablement dit « presque ».', 'L\'événement sera résumé comme « une occasion », et c\'est juste.',
    'Il y avait là de quoi se réjouir, ou pas.', 'Le gardien conserve une expression d\'une neutralité exemplaire.',
    'Du côté de {att}, on se contentera d\'avoir essayé.', 'La séquence se termine, comme prévu par {g}.', 'Personne ne s\'en plaindra, sauf {t}.',
  ],
  CHUTE_ARRETS_NOMBREUX: [
    '{g} signe {n} arrêts, et personne ne lui a demandé de ralentir.', 'À {n} arrêts, {g} a droit à une pensée de la production.',
    '{n} arrêts pour {g}, un chiffre que le comptable de l\'équipe a déjà vérifié.', 'Le total de {g} atteint {n} arrêts, ce qui se constate.',
    '{n} arrêts : {g} commence à prendre la chose personnellement.', 'À {n} arrêts, {g} mérite au moins qu\'on le salue de loin.',
    '{g} en est à {n} arrêts, soit un travail à temps plein.', '{n} arrêts, et le gardien ne semble pas avoir d\'opinion là-dessus.',
    'Notre statisticien note {n} arrêts pour {g} et demande un peu de calme.', '{g} cumule {n} arrêts, ce qui fait de lui un homme occupé.',
    'Avec {n} arrêts, {g} est l\'employé du mois, sinon de l\'année.', '{n} arrêts : l\'équipement de {g} mérite une mention.',
  ],
  CHUTE_ARRET_SERRE: [
    'Il reste {r} : on ne fera pas de commentaire sur le rythme cardiaque.', 'À {r} de la fin, chaque arrêt compte, y compris ceux qu\'on ne remarque pas.',
    'Dans un match aussi serré, un arrêt à {r} de la fin pèse plus lourd que sa taille.', 'Il reste {r}, et le tableau indicateur retient son souffle.',
    'À {r} du terme, on ne peut qu\'admirer la sobriété du geste.', 'Dans les circonstances, un arrêt est une prise de position.',
    'Le genre d\'arrêt dont on se souvient quand on essaie de se souvenir de quelque chose.', 'À {r} de la fin, la rondelle prend sa mission au sérieux.',
    'Il reste {r} : tous les détails sont maintenant des événements.', 'Un arrêt de ce calibre, à ce moment, mérite une minute de silence, ou presque.',
    'Il reste {r}, et chaque rondelle ressemble à un procès-verbal.', 'Notre statisticien dit que c\'est important, et il a l\'air d\'y croire.',
    'À {r} de la fin, personne ne regarde ses souliers, sauf les gardiens.', 'Il reste {r} : on peut maintenant parler d\'un arrêt d\'importance.',
    'Un arrêt à {r} de la fin, ça se facture au tarif de nuit.',
  ],
  CHUTE_ARRET_POUSSE: [
    'Le plan de {att} : continuer jusqu\'à ce que ça fonctionne.', 'Du côté de {att}, on garde la foi, ou du moins le calendrier.',
    'Chez les partisans de {att}, on commence à croire à la persistance.', 'Le banc de {att} a décidé d\'insister poliment.',
    'La pression de {att} se maintient, au sens strict du terme.', 'Du côté de {def}, c\'est une période où il faut tenir, c\'est tout.',
    'Le retard force {att} à une certaine éloquence offensive.', 'À {att}, on essaie les choses dans l\'ordre, et ça continue.',
    'La stratégie de {att} se résume maintenant à tirer plus souvent.', 'Le banc de {def} ne dit rien, ce qui en dit long.',
    'Quand on tire de l\'arrière, chaque rondelle est une promesse, même ratée.', 'La remontée de {att} est un projet à moyen terme.',
    'Le retard de {att} a des effets observables sur sa politique de tirs.', 'On sent du côté de {att} une ferme intention de corriger le pointage.',
  ],
  CHUTE_VEDETTE: [
    '{t} compte {n} buts cette saison, mais ce soir il y a eu un malentendu.', 'Pour un homme à {n} buts cette saison, {t} a droit à une rondelle de ratée.',
    '{n} buts cette saison : {t} rate rarement, et il le fait avec élégance.', '{t} et ses {n} buts cette saison ne se laissent pas démonter.',
    'À {n} buts cette saison, {t} a le droit de manquer un tir, mais pas de s\'y habituer.', 'On ne remet pas en cause les {n} buts de {t} cette saison.',
    '{t} ajoutera ça à son dossier, en regard de ses {n} buts cette saison.', 'Les {n} buts de {t} cette saison n\'ont rien pu faire pour celui-là.',
    'Il faut dire que {t} a {n} buts cette saison, ce qui crée des attentes.', 'Avec {n} buts cette saison, {t} peut se permettre une exception.',
  ],
  CHUTE_BLANCHISSAGE: [
    'Le zéro de {g} tient toujours, et le gardien n\'en fait pas un plat.', '{g} garde son tableau vierge, comme une page blanche.',
    'Aucun but contre {g} : la statistique est fragile, mais elle existe.', 'On ne parle pas de blanchissage, par superstition, mais {g} y pense peut-être.',
    'Le zéro de {g} est maintenant un sujet de conversation, malgré lui.', '{g} protège son zéro avec un soin presque domestique.',
    'Le dossier de {g} reste vierge, à ce stade.', 'Pas un seul but derrière {g}, ce qui est une façon de dire les choses.',
    '{g} entretient son blanchissage comme on entretient un jardin.', 'Le tableau de {g} affiche un zéro, et personne n\'ose y toucher.',
    'Notre recherchiste a vérifié : le zéro de {g} est bien un zéro.', 'Ce zéro derrière {g} est un travail d\'équipe, mais surtout un travail de {g}.',
  ],

  /* ---------- les séquences arrêtées ---------- */
  ACTION_SEQUENCE: [
    'Le système de {att} se déroule sans accroc, {t} reçoit au bout', 'Un enchaînement de {att} conforme au schéma, {t} se présente',
    'Le plan de {att} s\'exécute avec un sérieux d\'examen, {t} termine le travail', 'Le jeu de {att} se déploie comme sur papier, {t} lance',
    'Une séquence de {att} qu\'on pourrait montrer à des étudiants, {t} tire', 'Les passes de {att} sont d\'une précision administrative, {t} lance au bout',
    'Tout fonctionne du côté de {att}, jusqu\'à {t}', 'La procédure de {att} se déroule, {t} reçoit au dernier maillon',
    'La rondelle de {att} traverse la zone en bonne et due forme, {t} décoche', 'Un jeu soigné de {att}, qui se termine sur le bâton de {t}',
    'Le système de {att} va jusqu\'au bout, {t} en profite', 'La mécanique de {att} tourne, {t} en est le dernier engrenage',
    'Un jeu planifié par {att} aboutit à {t}', 'Le plan de {att} suit son cours : {t} tire', 'La séquence de {att} compte trois gestes, {t} la conclut',
    'Les avants de {att} se parlent poliment sur la glace, {t} lance', 'La rondelle de {att} passe de main en main, {t} reçoit le colis',
    'Dans les règles de l\'art de {att}, {t} se retrouve au bon endroit', 'La circulation de {att} est méthodique, {t} reçoit à point',
    'Le dessin de {att} produit son effet, {t} tente de conclure', 'Du côté de {att}, tout est en ordre, et {t} lance',
    'Un jeu répété de {att} se met en pratique avec {t}', 'Une séquence de {att}, pensée pour cet instant, aboutit à {t}',
    'La rondelle passe de main en main, {t} l\'attend', 'Un jeu de {att} qui mérite une note, {t} tire',
  ],

  /* ---------- les beaux jeux défensifs ---------- */
  CRI_DEFENSE: [
    'Voilà du travail sans bavure.', 'Rien d\'excitant, et c\'est ce qui est beau.', 'Admirable, dans un registre discret.',
    'Du hockey qui se passe de spectateurs.', 'Une démonstration de rigueur.', 'Fait à signaler : il ne s\'est rien passé.',
    'On applaudit l\'absence d\'incident.', 'La technique, dans sa forme la plus austère.', 'Zéro risque, zéro histoire.',
    'Voilà ce qu\'on appelle un ménage bien fait.', 'Une belle leçon de prudence.', 'Rien n\'a été laissé au hasard, sauf le reste du match.',
  ],
  ACTION_DEFENSE: [
    'La défensive de {def} referme le dossier avant qu\'on l\'ouvre', 'Le jeu de {def} règle ça en zone neutre, sans cérémonie',
    'Le travail discret de {def} porte ses fruits', 'Un joueur de {def} se retrouve exactement où il devait être',
    'Le repli de {def} éteint l\'attaque de {att} avec une grande économie de moyens', 'Le système de {def} applique le manuel à la page voulue',
    'La lecture de {def} coupe la route sans que personne s\'en aperçoive', 'Un défenseur de {def} lit le jeu comme on lit un contrat',
    'Le placement de {def} retire à {att} toute envie de continuer', 'La défensive de {def} gère la rondelle comme un dossier sensible',
    'Un joueur de {def} dégage la rondelle avec la discrétion d\'un huissier', 'Le repli de {def} s\'effectue selon le protocole',
    'La discipline de {def} désamorce la séquence de {att} par pure application', 'Le travail de {def} intercepte le plan de {att} avant qu\'il devienne un souvenir',
    'La patience de {def} rend l\'attaque de {att} aussi vaine qu\'un mardi', 'La défensive de {def} fait de la zone neutre un terrain sans issue',
    'Du côté de {def}, on a lu le jeu, et la lecture était bonne', 'Le refus de {def} à l\'attaque de {att} est bien documenté',
    'La défensive de {def} amortit la menace sans changer d\'expression', 'Le positionnement de {def} occupe tout l\'espace, y compris celui qu\'on ne voyait pas',
    'Le sens du devoir de {def} prive l\'attaque de {att} de son seul moment d\'espoir', 'Un défenseur de {def} sort la rondelle de la zone avec un calme de bibliothécaire',
    'Le jeu sans rondelle de {def} est ce qui sauve la situation', 'L\'organisation de {def} fait son œuvre, sans bruit ni photographe',
    'Un joueur de {def} prend la bonne décision, en silence', 'Le travail de {def} est d\'une régularité que les statistiques ne mesurent pas',
  ],
  CHUTE_DEFENSE: [
    'Rien ne figurera sur la feuille de match, et c\'est tout à leur honneur.', 'Du côté de {att}, il faudra revoir le dossier.',
    'Une action sans éclat, mais dans les règles de l\'art.', 'Le tableau indicateur n\'a rien à signaler, ce qui est une réussite.',
    'Voilà le genre d\'action qu\'on ne remarque que par son résultat.', 'L\'entraîneur de {def} y voit un modèle de sobriété.',
    'Un jeu si propre qu\'on pourrait le suspendre au mur.', '{att} n\'a pas eu le temps de s\'en rendre compte.',
    'Il faut un certain talent pour ne rien laisser arriver.', 'Les statisticiens ne savent pas où classer ça, et c\'est bon signe.',
    'Un exemple de défense qu\'on ne présente pas, on le vit.', 'Le réalisateur n\'a pas jugé utile de reprendre la séquence.',
    'On reconnaît ce genre de travail à son absence de conséquence.', 'Du côté de {att}, la leçon est claire, mais personne ne la lit.',
    'C\'est du hockey qui se conjugue au passé simple.', 'On ne gagne pas de prix pour ça, mais on gagne des matchs.',
    'Le jeu de {att} reste au stade de projet.', 'Ça ne se voit pas à la télé, mais ça se sent au banc.',
    'Un bon repli, c\'est comme un bon rapport : on ne le lit pas, on le suppose.', 'La défensive de {def} a fait sa journée sans qu\'on le remarque.',
  ],
  ACTION_BLOQUE: [
    'Le désavantage de {def} garde son poste : {att} tire de loin', 'La boîte de {def} garde sa forme, {att} se contente d\'un tir de loin',
    'Les unités de {def} fournissent le service minimum, et c\'est suffisant', 'Un joueur de {def} s\'interpose avec un sens aigu du devoir',
    'Le désavantage de {def} laisse {att} tirer de loin, comme convenu', 'La boîte de {def} se resserre, le jeu de {att} se rabat sur un tir de la pointe',
    'La discipline de {def} en désavantage oblige {att} à la patience', 'Un patineur de {def} bloque la trajectoire, sans commentaire',
    'La boîte de {def} remplit sa fonction avec une régularité d\'horloge', 'Le jeu de puissance de {att} se limite à un tir sans histoire',
    'La stratégie de {def} en infériorité est de ne rien offrir, et ça fonctionne', 'Le désavantage de {def} réduit l\'espace de {att} à quelques pouces',
    'Les patineurs de {def} font de la boîte un lieu inhospitalier', 'Un joueur de {def} se met devant la rondelle, par conscience professionnelle',
  ],
  CHUTE_BLOQUE: [
    'L\'avantage numérique de {att} manque un peu de relief.', 'Le jeu de puissance de {att} cherche encore son inspiration.',
    'Les secondes s\'écoulent, et la boîte de {def} les compte avec satisfaction.', 'L\'avantage de {att} se consume sans bruit.',
    'En désavantage, la boîte de {def} a au moins la simplicité pour elle.', 'Le banc de {def} observe la montre avec une discrétion admirable.',
    'L\'unité de {att} a le temps, mais elle n\'a pas l\'espace.', 'Chaque seconde de désavantage est une petite victoire administrative pour {def}.',
    'Le jeu de puissance de {att} ressemble à une réunion qui n\'aboutit pas.', 'Sur le banc de {def}, on compte les secondes comme on compte ses sous.',
    'L\'avantage numérique de {att} exige maintenant des résultats, et il n\'en a pas.', 'Du côté de {att}, c\'est un avantage théorique.',
    'Le temps passe, et l\'avantage de {att} avec lui.', 'La boîte de {def} gagne des points sans en inscrire.',
  ],

  /* ---------- les tirs ordinaires ---------- */
  ACTIONS_TIR: [
    ['{t} lance, sans conviction particulière', ''], ['Tir de {t} à des fins statistiques', ''], ['{t} tire par acquit de conscience', ''],
    ['Un tir de {t} de ceux qu\'on fait pour que la feuille ne reste pas vide', ''], ['{t} lance, conformément aux usages', ''],
    ['{t} dépose un tir de principe', ''], ['Tir poli et sans suite de {t}', ''], ['{t} envoie la rondelle vers le filet, à toutes fins utiles', ''],
    ['Tir de routine de {t}', ''], ['{t} tire, au cas où', ''], ['{t} lance, et la rondelle se met en route', ''],
    ['Tir de la pointe de {t} dans les délais habituels', 'D bleue'], ['{t} décoche de la ligne bleue, sans surprise', 'D bleue'],
    ['Lancer frappé de {t} conforme à ce qu\'on en attendait', 'canon bleue'], ['{t} lance du revers, avec une prudence marquée', 'F fab'],
    ['Tir des poignets de {t}, d\'une sobriété exemplaire', 'tireur'], ['{t} lance en entrée de zone, sans y voir malice', 'F rapide contre'],
    ['Tir de {t} sur l\'avantage numérique à titre indicatif', 'AN'], ['{t} dégage le danger d\'un tir lointain, en désavantage', 'DN'],
    ['Tir précipité de {t} sous la pression de l\'échec avant', 'echec'], ['{t} lance de derrière la ligne, sans conséquence', 'F derriere'],
    ['Un tir de {t} dans la circulation sans rien qui demande un communiqué', 'bleue'], ['{t} essaie une passe à lui-même, qui devient un tir', 'F fab'],
    ['Tir de {t} de ceux dont on se souvient par obligation', ''], ['{t} tente un tir lointain, comme prévu au plan de la soirée', 'D'],
  ],
  ISSUE_TIR: [
    '{g} le voit venir de loin', '{g} s\'en occupe sans lever un sourcil', '{g} remet la rondelle en circulation avec courtoisie',
    '{g} encaisse ça comme une formalité', 'rien de grave pour {g}', '{g} est exactement où il fallait', '{g} répond d\'un geste calme',
    '{g} classe l\'affaire sans la lire', '{g} s\'en tire avec un minimum de mouvement', 'un dossier bien simple pour {g}',
    '{g} accueille le tir avec la sobriété d\'un portier', 'un arrêt sans histoire pour {g}', '{g} contrôle, puis remet à plus tard',
    '{g} ne s\'en formalise pas', '{g} l\'attrape comme on attrape un courriel', '{g} y voit à peine une sollicitation',
    '{g} range ça dans la catégorie « routine »', '{g} accepte, par politesse', '{g} détourne l\'attention et la rondelle',
    '{g} fait preuve d\'un flegme constaté', '{g} fait ce qu\'on lui demande', '{g} y répond par un haussement d\'épaules mental',
    '{g} se contente de se tenir là', '{g} l\'immobilise sans changer de visage', '{g} s\'en occupe par déférence pour le règlement',
  ],

  /* ---------- les buts ---------- */
  CRI_BUT: [
    'Le tableau indicateur est informé.', 'Voilà qui change le pointage.', 'Un but, donc.', 'La lumière rouge confirme.', 'On me dit que c\'est un but.',
    'Nous avons un but.', 'La rondelle a franchi la ligne, selon toutes les apparences.', 'Fait avéré : but.',
    'Les juges de but sont d\'accord.', 'Ça compte.', 'Voilà un résultat.', 'Le filet est au courant.',
    'On inscrit un but à la feuille.', 'Le pointage vient d\'évoluer.', 'Eh bien, voilà.', 'Le chronométreur prend note.',
    'Le but est confirmé par les instruments.', 'La rondelle est dans le filet, sans équivoque.', 'Ce but a été homologué en direct.',
    'Rien à ajouter : but.', 'La preuve est dans le filet.', 'Un but, avec toutes les pièces justificatives.',
    'Voilà qui se rangera dans la colonne des buts.', 'Un but vient de se produire.', 'C\'est officiel, ou presque.',
  ],
  APPUI_SOLO: [
    'sans avoir consulté personne', 'en s\'occupant lui-même de la paperasse', 'sans que l\'équipe n\'ait eu à être mise au courant',
    'sans avoir demandé d\'avis', 'sur une initiative strictement personnelle', 'en l\'absence de tout comité',
    'à titre individuel', 'sans déranger un coéquipier', 'après un trajet sans assistance, mais avec résultat',
    'en réglant l\'affaire à lui seul', 'sans aide, et sans en faire de cas', 'en cavalier seul, selon l\'expression',
  ],
  APPUI_SEQUENCE: [
    'après une consultation à trois', 'au bout d\'une démarche collective bien rodée', 'avec l\'aide de deux collègues dûment identifiés',
    'à l\'issue d\'un travail d\'équipe attesté', 'sur un enchaînement que l\'entraîneur ne désavouera pas',
    'au terme d\'une chaîne de décisions concordantes', 'après que deux coéquipiers eurent été mis dans le coup',
    'sur un projet commun mené à terme', 'au bout d\'un jeu de passes approuvé par tous les intéressés',
    'après une concertation sans accroc', 'sur un jeu de passes digne d\'un dossier bien monté', 'avec une logistique irréprochable',
  ],
  CONTEXTE_BUT: {
    premier: ['La première inscription met fin au concept abstrait du pointage.', 'Première pierre du pointage : on avait le temps de s\'ennuyer, on ne l\'a plus.',
      'Première inscription au tableau, qui perd ainsi son air de gare désaffectée.', 'Le tableau indicateur, première affectation de la soirée, se met au travail.',
      'Voilà une ouverture de marque qu\'on ne regrettera pas, pour {eq}.', 'Le dossier est ouvert, du côté de {eq}.',
      'La première page du procès-verbal est remplie.', 'Le match a maintenant une histoire, et {eq} en a la première ligne.'],
    egalite: ['Retour à l\'égalité, équilibre naturel du tableau : {s}.', 'L\'égalité rend tout théoriquement possible, {s}.', 'Égalité des deux côtés, avec la même quantité de buts : {s}.',
      'L\'égalité à {s} satisfait les amateurs de symétrie.', 'Le match est de nouveau égal, et c\'est un nouveau match : {s}.',
      'Du côté de {eq}, l\'écart est effacé : {s}.', 'Il y a maintenant égalité, et le mot est pris dans son sens strict : {s}.',
      'Le tableau indique l\'égalité, {s}, ce que personne ne peut contester.', 'Avec {s}, rien ne départage les équipes : c\'est l\'égalité.',
      'Du côté de {autre}, l\'avance s\'est évaporée : c\'est l\'égalité, {s}.'],
    devant: ['Du côté de {eq}, c\'est l\'avantage, ténu mais réel : {s}.', 'Le pointage est de {s}, et un camp vient de le remarquer.',
      'L\'égalité n\'aura duré qu\'un temps, {s}.', 'La marque est de {s}, ce qui redonne un sens au mot « avance ».',
      'Voilà {eq} devant, d\'un seul but, mais devant : {s}.', 'Le tableau passe à {s}, au bénéfice de {eq}.',
      'Du côté de {eq}, un premier pas vers la victoire, {s}.', 'On compte maintenant {s}, et on sait qui compte le plus.',
      'L\'avantage d\'un but, c\'est mince, mais ça se mesure : {s}.', 'Du côté de {autre}, la situation exige maintenant une réaction.'],
    creuse: ['La marge de {eq} est de {n} buts, ce qui est confortable, au sens administratif.', 'Du côté de {eq}, l\'avance de {n} buts est une bonne nouvelle.',
      'On commence à parler de contrôle, {s}.', 'Le pointage de {s} laisse peu de place à l\'interprétation.',
      'Une marge de {n} buts, c\'est un coussin, dans le vocabulaire de la maison.', 'Du côté de {autre}, le chemin du retour s\'allonge, {s}.',
      'La soirée de {eq} prend une forme plus rassurante : {s}.', 'Les {n} buts d\'avance de {eq} font l\'objet d\'une certaine sérénité.',
      'L\'écart de {n} buts pour {eq} est de ceux qu\'on observe avec intérêt.', 'Le tableau ne ment pas : {s}.'],
    raclee: ['La raclée est en cours : {s} est désormais un événement en soi.', 'Du côté de {autre}, la soirée est un cauchemar difficile à résumer.',
      'Cette raclée, {s}, mériterait une conférence de presse.', 'Une avance de {n} buts : du côté de {eq}, on ne lève pas le pied.',
      'Du côté de {autre}, on regarde le tableau avec recueillement, et on se sait dépassé.', 'Cette raclée de {s} se commente d\'elle-même.',
      'Les partisans de {autre} songent à quitter avant le souper.', 'La raclée de {s} réclame des mots que le commentateur n\'a pas.'],
    reduit: ['Du côté de {eq}, l\'écart est maintenant de {n}, ce qui laisse une ouverture.', 'Le retard de {eq} se réduit, {s}.',
      'Le match reprend un souffle administratif : {s}.', 'Du côté de {autre}, l\'avance se fait plus modeste, {s}.',
      '{s}, ce qui rend le reste du dossier plus intéressant pour {eq}.', 'Le tableau passe à {s}, et {autre} est prié de réfléchir.',
      'Du côté de {eq}, l\'effort est récompensé, partiellement : {s}.', 'L\'écart est de {n}, ce qui change tout et rien à la fois.'],
    doublé: ['Deux buts pour lui : la feuille de match lui fait une place.', 'Il en est à deux, et la paperasse s\'allonge.',
      'Un doublé, ce qui mérite au moins une ligne dans le résumé.', 'Voilà son deuxième, et les suivants sont à la discrétion de la soirée.',
      'Deuxième but du joueur, le tableau commence à reconnaître son nom.', 'Il double la mise, selon l\'expression consacrée.',
      'Les deux buts ont été homologués séparément.', 'C\'est un doublé, ce qui est exactement deux de plus que zéro.'],
    chapeau: ['Trois buts : le préposé aux chapeaux est informé.', 'Tour du chapeau, ce qui oblige à quelques formalités.',
      'Voilà un tour du chapeau, et le mot « chapeau » prend tout son sens.', 'Trois buts : le tour du chapeau le place dans une catégorie dont on parle.',
      'Le tour du chapeau sera consigné à la feuille, et à la mémoire des partisans.', 'Il complète son tour du chapeau, au grand soulagement de la rubrique.'],
    festival: ['{n} buts pour {m} : à ce stade, c\'est un dossier.', 'Le total de {m} atteint {n}, ce qui n\'est pas prévu au protocole.',
      '{n} buts pour {m}, et la production cherche un adjectif.', 'À {n} buts, {m} dépasse ce que la feuille de match avait prévu.',
      'Le compte de {m} est de {n} buts, ce qu\'on constate sans explication.'],
    an: ['L\'avantage numérique a rempli sa mission, comme décrit.', 'Le jeu de puissance a produit un but, ce qui est son but.',
      'L\'unité d\'avantage numérique a fait ce pour quoi elle a été formée.', 'L\'avantage numérique rapporte, comme sur le plan.',
      'La punition vient de coûter un but, ce qui est son principal effet.', 'La supériorité numérique du jeu de puissance a produit un résultat tangible.',
      'Le jeu de puissance avait un objectif, et il est atteint.', 'On notera que l\'avantage numérique a fonctionné, ce qui arrive.',
      'La punition vient d\'ouvrir la boîte, comme souvent.', 'La punition a eu des suites, et elles sont au tableau.'],
    dn: ['Un but en désavantage numérique : le règlement n\'avait pas prévu ça.', 'Un but à court d\'un joueur est une fantaisie bienvenue.',
      'Le désavantage vient de marquer, ce qui est peu orthodoxe.', 'Le jeu de puissance adverse retourne à la case départ.',
      'Il faudra expliquer à l\'unité d\'avantage numérique ce qui vient de se passer.', 'Un but à court d\'un joueur, et le protocole en prend un coup.',
      'L\'avantage numérique est devenu un sujet de réflexion pour l\'autre camp.', 'Le but, en infériorité, est dans la catégorie des surprises documentées.'],
    special: ['Le jeu s\'est déroulé comme au tableau, et le tableau avait raison.', 'Du côté de {eq}, la répétition porte fruit.',
      'La séquence a été exécutée selon les consignes de l\'entraîneur.', 'Le plan de {eq} a fonctionné, ce qui est le but d\'un plan.',
      'Un but qui se résume à : ils l\'avaient prévu.', 'Voilà un jeu qu\'on pourrait montrer aux jeunes, à condition qu\'ils aiment les schémas.',
      'La mécanique de {eq} vient de livrer son résultat.', 'Le système a produit un but, ce qui est à la fois son plan et sa preuve.'],
    bleue: ['La pointe de {eq} a bien fait son travail.', 'Le tir de loin a trouvé son chemin, comme les ingénieurs l\'avaient prévu.',
      'La stratégie de la ligne bleue s\'avère payante, du moins ce soir.', 'Du côté de {eq}, tout part de la ligne bleue et tout y retourne.',
      'La pointe de {eq} a déposé son rapport au fond du filet.'],
    contre: ['La contre-attaque de {eq} a livré le résultat attendu.', 'Du côté de {autre}, le revirement a coûté un but, ce qui est cher.',
      'Une transition rapide, un but : la mathématique est simple.', 'La vitesse de {eq} a pris la défensive en défaut.',
      'On a vu une contre-attaque qui, cette fois, a fini par aboutir.'],
    derriere: ['Le jeu derrière le filet a produit un résultat concret.', 'Le plan de {eq} derrière la ligne des buts est confirmé par les faits.',
      'Le gardien a regardé du mauvais côté, et le mauvais côté avait raison.', 'La manœuvre derrière le filet a bien fonctionné.',
      'Du côté de {eq}, la zone derrière les buts est un lieu de travail productif.'],
    courtes: ['Les passes courtes de {eq} ont atteint leur objectif, de proche en proche.', 'Une série de gestes brefs, un but : l\'économie du geste.',
      'La défensive a vu passer la rondelle de main en main, sans pouvoir objecter.', 'Du côté de {eq}, les petites passes ont rapporté gros.',
      'Le jeu de passes courtes a fait son œuvre, lentement mais sûrement.'],
    echec: ['L\'échec avant de {eq} vient de produire un revirement et un but.', 'La pression a payé, et le résultat est au tableau.',
      'Du côté de {autre}, la sortie de zone s\'est avérée plus compliquée que prévu.', 'Le travail d\'échec avant a porté ses fruits en un seul geste.',
      'La défensive de {autre} a été prise en pleine réflexion.'],
    defensive: ['La patience de {eq} a été récompensée par un seul geste.', 'Un jeu défensif, un but : l\'efficacité se mesure comme on veut.',
      'Du côté de {eq}, il aura suffi d\'attendre le bon moment, et il est arrivé.', 'Le plan prudent de {eq} s\'est conclu par un but réfléchi.',
      'La discipline de {eq} a trouvé sa récompense, au moment prévu.'],
    tard: ['À {r} de la fin, ce but a de la gueule, selon le jargon.', 'Il reste {r} : ce but ne passera pas inaperçu.',
      'Un but à {r} de la fin, dans la catégorie des buts dont on parle encore.', 'Il reste {r}, et chaque seconde vient de changer de valeur.',
      'Du côté de {autre}, il reste {r} pour réparer ça, ce qui est peu.', 'À {r} du terme, on ne peut plus dire que ce but est sans conséquence.',
      'Il reste {r} : un but à ce moment-ci est un événement d\'État.', 'À {r} de la fin, le tableau a maintenant de l\'importance.',
      'Un but de cette nature, à {r} de la fin, a l\'effet d\'une annonce officielle.', 'Il reste {r}, ce qui est à la fois court et suffisant.'],
    prolongation: ['La prolongation prend fin sur ce but, ce qui simplifie la suite.', 'Du côté de {eq}, la prolongation vient de livrer son verdict.',
      'La mort subite a été brève et décisive, comme prévu.', 'Voilà le but qui règle la prolongation pour {eq}.',
      'Le procès-verbal de la prolongation est clos à ce moment précis.', 'Rien de plus à décider en prolongation : la victoire va à {eq}.',
      'Le but de la prolongation est marqué, et le match avec lui.', 'Du côté de {autre}, la mort subite met fin à la soirée, administrativement.'],
  },

  /* ---------- les punitions ---------- */
  INFRACTIONS: [
    'retenue', 'mauvaise conduite', 'coup de bâton', 'avoir gêné un adversaire', 'avoir joué du bâton avec trop de zèle',
    'avoir frappé un patin', 'avoir agrippé un chandail', 'avoir levé le bâton à une hauteur illégale', 'avoir bousculé hors du jeu',
    'avoir tenu le mauvais bout du bâton', 'avoir refusé de céder le passage', 'avoir contrarié un adversaire sans la rondelle',
  ],
  PHRASE_PUNITION: [
    'Un sifflet, une décision : {j} en subit les conséquences pour {inf}.', '{j} est invité à s\'asseoir pour {inf}.',
    'L\'arbitre consulte son jugement et son règlement : {j}, {inf}.', '{j} se dirige vers le banc des punitions, motif : {inf}.',
    'Pour {inf}, {j} prend le chemin habituel.', 'Après délibération express, {j} est puni pour {inf}.',
    '{j} paie le prix, selon le tarif officiel : {inf}.', 'Sanction pour {j} : {inf}, dans les formes.',
    '{j} reçoit une punition pour {inf}, ce qu\'il ne contestera pas longtemps.', 'L\'arbitre dresse un constat : {j}, {inf}.',
    '{j} quitte la glace, officiellement pour {inf}.', 'Le rapport d\'arbitre est clair : {inf}, et {j} s\'en va.',
  ],
  PHRASE_PUNITION_EQUIPE: [
    'L\'arbitre inscrit une punition à {autre} pour {inf}.', 'Pénalité de {autre} pour {inf}, l\'un de ses patineurs s\'en va au banc.',
    'Pour {inf}, un patineur de {autre} est sanctionné.', 'Le banc de {autre} perd un homme pour {inf}.',
    'Un joueur de {autre} est puni pour {inf}, sans autre forme de procès.', 'Le motif invoqué est {inf}, et {autre} doit l\'acquitter.',
  ],
  PHRASE_AVANTAGE: [
    'Voilà un joueur de plus pour {eq}, pour le meilleur ou pour le pire.', 'Le jeu de puissance de {eq} est convoqué.',
    'La supériorité numérique est maintenant du côté de {eq}, c\'est un fait.', 'Du côté de {eq}, le règlement prévoit une occasion de faire valoir ses arguments.',
    'L\'unité de {eq} entre en scène avec le sérieux de circonstance.', 'Un avantage numérique est consenti à {eq}, sans conditions.',
    'Le tableau indicateur confirme l\'avantage numérique de {eq}.', 'Un patineur de plus pour {eq}, dans la mesure de ses moyens.',
  ],
  COULEUR_PUNITION: [
    'L\'arbitre a consulté son carnet avec gravité.', 'Une décision prise avec le sérieux d\'un magistrat.', 'On entend un murmure poli dans les gradins.',
    'Le banc a reçu la nouvelle avec un détachement de circonstance.', 'La logique du règlement est sauve, ce qui est déjà quelque chose.',
    'Le chroniqueur de couleur y voit un cas d\'école.', 'La punition est mineure, mais le sujet est majeur.', 'Le geste a été vu, jugé, et inscrit au registre.',
    'Rien de scandaleux, juste du règlement appliqué.', 'On pourra en débattre à la pause, avec modération.',
    'Les statisticiens ajoutent une ligne à leur tableau des punitions.', 'Il y a ici de la matière pour un chapitre de manuel.',
    'La foule observe la suite avec un intérêt retenu.', 'Un incident sans éclat, mais avec toutes ses formalités.',
    'La décision est conforme au livre, et le livre est épais.', 'L\'arbitre fait son métier, c\'est tout ce qu\'on lui demande.',
    'Le banc de punitions accueille un nouvel arrivant sans fanfare.', 'On se souviendra de cette punition pour environ quarante secondes.',
    'Le geste fautif a été commis avec un naturel déconcertant.', 'Cela ne figurera pas dans les faits saillants, mais cela figurera au registre.',
  ],
  COULEUR_PUNITION_TARD: [
    'À cette heure du match, une punition est un événement officiel.', 'Une punition à ce moment est une affaire d\'État.',
    'Si près de la fin, la décision pèse son poids, et même un peu plus.', 'Le banc fixe maintenant l\'horloge avec une attention soutenue.',
    'Dans les dernières minutes, le règlement acquiert une valeur supplémentaire.', 'Voilà le genre de punition qui s\'ajoute au dossier de la soirée.',
    'Un moment critique pour s\'asseoir, dans la liste des mauvais moments.', 'La fin approche, et la punition aussi, dans l\'ordre.',
  ],
  RETOUR_PUNITION: [
    '{j} revient au jeu, réhabilité aux yeux du règlement.', '{j} sort du banc des punitions, un peu plus sage.', '{j} reprend sa place, le dossier classé.',
    'La peine de {j} est purgée, et il retrouve la glace.', '{j} est de retour, sans conséquence administrative.', '{j} réintègre le jeu avec un air de réflexion.',
    'Après l\'attente, {j} retrouve ses collègues.', '{j} est libéré de ses obligations pénales.',
  ],
  RETOUR_EQUIPE: [
    'La punition est expirée, le jeu reprend à force égale.', 'Le patineur puni est de retour, sans fanfare.',
    'Les équipes sont de nouveau à effectifs complets.', 'L\'attente est terminée, et on reprend le cours normal des choses.',
  ],
  COULEUR_RETOUR: [
    'Le désavantage de {eq} a survécu sans concéder de but à l\'avantage.', 'Du côté de {autre}, l\'avantage numérique n\'a pas donné de but.',
    'Les unités de {eq} sortent de la boîte avec le sentiment du devoir accompli.', 'La supériorité numérique de {autre} s\'est éteinte sans bruit.',
    'Du côté de {eq}, c\'est une affaire réglée, et sans but à l\'avantage.', 'L\'avantage de {autre} se termine sur un constat d\'échec poli.',
    'Le désavantage de {eq} a fait preuve d\'une discipline remarquable.', 'La boîte de {eq} peut rendre les clés, en bon état.',
    'Du côté de {autre}, c\'est un jeu de puissance qui n\'a pas porté fruit.', 'Le bilan de la punition : aucun but à l\'avantage de {autre}.',
    'L\'unité de {eq} retourne à la case départ avec le sourire.', 'La punition s\'achève, et le but à l\'avantage reste à inventer pour {autre}.',
  ],

  /* ---------- le jeu physique ---------- */
  PHRASE_COUP: [
    '{j} informe {c} de la présence de la bande.', '{j} rencontre {c} avec une franchise que l\'arbitre juge acceptable.',
    '{j} dépose {c} contre la rampe, selon la procédure habituelle.', '{c} reçoit la visite de {j}, sans rendez-vous.',
    '{j} entre en contact avec {c}, et {c} le remarque.', '{j} complète une mise en échec sur {c} avec une précision de géomètre.',
    '{j} fait comprendre à {c} que la glace est partagée.', '{j} et {c} se croisent, et l\'un des deux en prend note.',
    '{c} se retrouve face à {j}, pour une courte discussion physique.', '{j} règle ses comptes avec {c} dans les limites du règlement.',
  ],
  COULEUR_COUP: [
    'Le geste est net, et le chroniqueur de couleur approuve du regard.', 'Le banc de {autre} observe la scène avec une neutralité douteuse.',
    'Un contact franc, sans commentaire superflu.', 'Les partisans réagissent avec un intérêt marqué.',
    'Le réalisateur choisit de reprendre l\'image, par déférence.', 'On se souviendra de ce contact environ jusqu\'à la prochaine mise au jeu.',
    'L\'arbitre juge que tout est dans l\'ordre, et le jeu reprend.', 'Rien qu\'un rappel que le hockey se joue à plusieurs.',
    'Le banc de {eq} approuve, discrètement.', 'Le geste est de ceux qu\'on explique mal à des enfants.',
  ],
  PHRASE_BAGARRE: [
    '{j} et {c} règlent un différend de longue date, ou de quarante secondes.', 'Les gants tombent entre {j} et {c}, par consentement mutuel.',
    '{j} propose à {c} un échange de vues plus direct.', 'Une discussion s\'engage entre {j} et {c}, sans interprète.',
    '{j} et {c} décident de se parler à poings fermés.', '{j} et {c} enlèvent leurs gants, avec le sérieux d\'un rendez-vous.',
  ],
  ISSUE_BAGARRE: {
    gagne: ['{g} remporte l\'échange, ce que les juges de ligne confirment.', 'L\'issue est claire : {g} l\'emporte et {p} l\'admet.',
      '{g} a le dernier mot, et {p} prend le temps de l\'écouter.', 'Le combat tourne à l\'avantage de {g}, dans les formes.',
      '{g} termine l\'échange en position avantageuse, {p} en position de réflexion.', '{p} reconnaît la supériorité de {g}, de manière non verbale.'],
    nul: ['Les deux protagonistes se quittent sans verdict, mais avec des souvenirs.', 'L\'échange se solde par une entente tacite.',
      'Les juges de ligne séparent deux hommes qui se comprennent.', 'On ne peut pas parler de vainqueur, seulement de participants.'],
  },
  COULEUR_BAGARRE: {
    gagne: ['Le banc de {eq} manifeste son appréciation, avec les moyens du bord.', 'Pour {g}, c\'est un point marqué à l\'extérieur du pointage.',
      'La foule suit {g} du regard jusqu\'au banc, avec respect.', 'On notera le travail de {eq} dans cette spécialité.',
      'Le combat de {g} est consigné au registre, section bagarres.'],
    nul: ['Rien de décisif, mais tout est consigné.', 'Les deux hommes iront méditer sur la question.', 'Un échange sans suite, mais avec un certain style.',
      'La bagarre se termine, comme elle a commencé : sans qu\'on ait demandé l\'avis du public.', 'Chacun a fait ce qu\'il avait à faire, et c\'est tout.'],
  },
  PHRASE_MELEE: [
    '{j} et {c} échangent quelques mots, à voix haute, devant le filet.', 'Un léger désaccord oppose {j} et {c}, dans la zone du gardien.',
    '{j} et {c} se bousculent poliment, après le sifflet.', 'Les nerfs de {j} et de {c} s\'expriment en même temps.',
    '{j} trouve {c} sur son chemin et lui en fait la remarque.', 'Le contact entre {j} et {c} se prolonge un peu au-delà du règlement.',
  ],
  COULEUR_MELEE: [
    'Les arbitres s\'interposent avec l\'autorité de leur fonction.', 'Un incident bref, mais qui a eu des témoins.',
    'Le ton monte, puis redescend, comme dans une réunion de syndic.', 'Chacun retrouve son banc, et ses idées.',
    'Rien de grave, juste un peu d\'humeur.', 'Les juges de ligne ont fait leur travail avec un calme de façade.',
  ],

  /* ---------- les périodes, le début, la fin ---------- */
  FIN_PERIODE: [
    'La sirène marque la fin de la {per}, sans surprise.', 'Voilà la {per} close, au sens du règlement.', 'La {per} s\'achève, comme prévu à l\'horaire.',
    'Le chronomètre arrive au bout de la {per}, sans l\'avoir cherché.', 'La {per} est maintenant derrière nous, et c\'est irréversible.',
    'Les joueurs saluent la fin de la {per} en quittant la glace.',
  ],
  COULEUR_PERIODE: {
    egal: ['Personne n\'a le dessus, sinon sur le papier.', 'Le tableau est parfaitement symétrique.', 'Rien ne penche, et c\'est un exploit statistique.',
      'Une égalité qu\'on dirait dessinée à la règle.', 'Les deux équipes se valent, pour l\'instant.', 'On ne peut pas départager les équipes, ce qui est un début de conclusion.',
      'La balance est stable, au sens physique.', 'Le pointage reste en équilibre, comme un meuble bien posé.'],
    mene: ['Du côté de {eq}, le pointage est de {s} en sa faveur.', 'Le tableau indique {s}, au bénéfice de {eq}.', 'Du côté de {eq}, l\'avance est réelle, quoique relative.',
      'Le pointage de {s} donne raison à {eq}, pour l\'instant.', 'On compte {s}, et on sait pour qui.', 'Du côté de {eq}, un vestiaire plus détendu que l\'autre.',
      'La marque de {s} est un fait, pas une opinion.', 'Le tableau indicateur favorise {eq}, selon ses propres calculs.'],
    tirs: ['Au chapitre des tirs, le contraste est notable en faveur de {eq}.', 'Du côté de {autre}, on a vu moins de rondelles.',
      'Du côté de {eq}, les tirs s\'accumulent, comme les documents sur un bureau.', 'La balance des tirs penche franchement pour {eq}.',
      'Du côté de {autre}, la période a surtout été un exercice de défense.', 'Le décompte des tirs favorise {eq}, avec une netteté certaine.'],
    prolongation: ['La prolongation s\'impose, faute d\'un résultat décisif.', 'On ajoutera quelques minutes de temps supplémentaire, par souci d\'équité.',
      'Un temps supplémentaire s\'impose pour trancher la question.', 'Il faudra se départager en prolongation, ce qui est le principe d\'un match.',
      'Le règlement prévoit une prolongation, et on va la lui donner.'],
  },
  DEBUT: [
    'Bonsoir, et la rondelle est mise en jeu.', 'La mise au jeu est faite, et le temps s\'écoule officiellement.', 'Le match débute, avec l\'aval de l\'arbitre.',
    'La première mise au jeu se déroule dans le calme.', 'Les équipes entrent en matière, on peut le dire ainsi.', 'Voilà, le chronomètre est lancé.',
  ],
  COULEUR_DEBUT: [
    'Les deux bancs semblent prêts, du moins en apparence.', 'On annonce un match, et un match il y aura.', 'Les gardiens se sont placés avec un sérieux de circonstance.',
    'Les arbitres ont consulté leurs montres, avec un air entendu.', 'L\'amphithéâtre a pris place, plus ou moins.', 'Les conditions sont normales, ce qui est déjà une victoire.',
    'Le tableau indicateur est opérationnel, selon nos informations.', 'La glace est, à première vue, de la glace.', 'Tout est en ordre, ou du moins en place.',
    'Les entraîneurs ont des plans, dont certains sont même écrits.', 'Les joueurs ont salué les gardiens, comme de coutume.', 'Aucun incident à signaler, pour l\'instant, c\'est un bon début.',
  ],
  FIN_MATCH: [
    'La sirène retentit, et le tableau reste ce qu\'il est.', 'Voilà, c\'est officiellement terminé.', 'Le match prend fin, avec l\'accord de toutes les parties.',
    'Plus rien à jouer, et le chronomètre le confirme.', 'La partie est terminée, ce qui était prévu.',
  ],
  COULEUR_FIN: {
    blanchissage: ['Un blanchissage pour {g}, et pas une phrase de plus à dire.', '{g} termine la soirée avec un zéro net, sans bavure.',
      'Le dossier de {g} est resté vierge, c\'est tout à son honneur.', 'Aucune rondelle n\'a franchi la ligne derrière {g} : le constat est limpide.',
      'La statistique de {g} s\'inscrit en zéro, ce qui est le résultat de son travail.'],
    raclee: ['Du côté de {autre}, le résultat sera discuté en privé.', 'Une soirée entièrement favorable à {eq}, ce que nul ne contestera.',
      'Le résultat parle de lui-même, et {autre} l\'écoute en silence.', 'Du côté de {eq}, une victoire qui n\'a pas fait de mystère.',
      'Du côté de {autre}, le trajet de retour sera sans doute silencieux.'],
    serre: ['Un seul but d\'écart, et tout le monde y a cru jusqu\'au bout.', 'Le résultat se joue à un but, ce qui est une façon élégante de gagner.',
      'À un but près, c\'était une autre histoire.', 'Un résultat étroit, que les deux vestiaires liront à leur façon.',
      'La différence est minime, et c\'est la seule qui compte.'],
    prolongation: ['Le règlement a prévu une suite, et elle a produit un résultat.', 'Le temps réglementaire n\'a pas suffi, et le temps supplémentaire non plus, au début.',
      'Un but sec a tranché ce qui ne l\'était pas.', 'La mort subite a pris une décision, comme elle sait le faire.',
      'On était parti pour durer, et on a duré, avant de conclure.'],
  },
};
